version: 0.2

env:
  secrets-manager:
    VITE_API_KEY: "arn:aws:secretsmanager:us-east-2:535146832369:secret:nutrition_api-xXnzCL"

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm ci
  pre_build:
    commands:
      - echo Running pre-build steps...
  build:
    commands:
      - echo Building the Vite React app...
      - npm run build
  post_build:
    commands:
      - echo Build completed successfully
      - echo "Deploying to S3..."
      - aws s3 sync dist/ s3://frontend-codebuildtest --delete

artifacts:
  files:
    - '**/*'
  base-directory: dist

cache:
  paths:
    - node_modules/**/*
